apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m7i-flex.large", "c7i-flex.large", "t3.small","t2.micro"]
    desiredCapacity: 3
    spot: true